name: Deploy URL Shortener

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      TF_WORKSPACE: url-shortener-prod  # <-- your isolated workspace name here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Go executable
        run: |
          cd backend
          GOOS=linux GOARCH=amd64 go build -o main

      - name: Build Docker image
        run: |
          docker build -t url-shortener-lambda backend/

      - name: Tag Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/url-shortener-lambda:latest"
          docker tag url-shortener-lambda:latest $IMAGE_URI

      - name: Push Docker image
        run: |
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/url-shortener-lambda:latest"
          docker push $IMAGE_URI

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Select Workspace
        run: |
          cd terraform
          terraform workspace select $TF_WORKSPACE || terraform workspace new $TF_WORKSPACE

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve
