name: PR Deploy - URL Shortener Dev

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  pr-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      WORKSPACE: url-shortener-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Initialize Go module and tidy dependencies
        working-directory: backend
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/sergeychernyshov-code/url-shortener/backend
          fi
          go mod tidy

      - name: Build Go executable
        working-directory: backend
        run: |
          GOOS=linux GOARCH=amd64 go build -o main

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image to ECR
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          IMAGE_TAG=pr-${PR_NUMBER}
          IMAGE_NAME=url-shortener-lambda
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${IMAGE_NAME}:${IMAGE_TAG}"

          docker build -t $IMAGE_NAME -f backend/Dockerfile backend/
          docker tag $IMAGE_NAME $IMAGE_URI
          docker push $IMAGE_URI

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Workspace Select or Create
        working-directory: terraform
        run: |
          terraform workspace list | grep -q "${{ env.WORKSPACE }}" \
            && terraform workspace select "${{ env.WORKSPACE }}" \
            || terraform workspace new "${{ env.WORKSPACE }}"

      - name: Terraform Apply (Dev)
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var "image_uri=${{ env.IMAGE_URI }}" \
            -var "environment=dev"
